name: test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: encode password
        id: encoded
        run: |
          PASSWORD=$(printf %s ${{ secrets.SSH_PASSWORD }} | jq -sRr @uri )
          echo "PASSWORD=$PASSWORD" >> $GITHUB_OUTPUT

      - name: get runner ip
        id: runner_ip
        run: |
          IP=$(curl https://api.ipify.org)
          echo "IP=$IP" >> $GITHUB_OUTPUT

      - name: whitelist ip on hosting (o2switch)
        shell: bash
        run: |
          ENDPOINT="frontend/o2switch/o2switch-ssh-whitelist/index.live.php"
          
          echo "Actual whitelist : "
          
          LIST=$(curl -sX GET "https://${{ secrets.SSH_USER }}:${{ steps.encoded.outputs.PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=list")
          echo "$LIST" | jq '.data.list[]'
              
