name: test
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: encode password
        id: encoded
        run: |
          password=$(printf %s ${{ secrets.SSH_PASSWORD }} | jq -sRr @uri )
          echo "password=$password" >> $GITHUB_OUTPUT

      - name: get runner ip
        id: runner_ip
        run: |
          response=$(curl https://api.ipify.org)
          echo "response=$response" >> $GITHUB_OUTPUT

      - name: purge whitelist and add runner ip to it Whitelist IP on hosting & delete github old ones (o2switch)
        shell: bash
        run: |
          ENDPOINT='frontend/o2switch/o2switch-ssh-whitelist/index.live.php'
          PARAM_LIST='?r=list'
          
          echo "Get actual whitelisted IPs..."
          RESPONSE=$(curl -sX GET "https://${{ secrets.SSH_USER }}:${{ steps.encoded.outputs.password }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT$PARAM_LIST")
          echo "Response: $RESPONSE"
          UNIQUE_IPS=$(echo "$RESPONSE" | jq -r '.data.list[] | .address' | sort -u)
          
          echo "Attempt to whitelist IP..."
          curl -sX POST -d 'whitelist[address]=${{ steps.runner_ip.outputs.response }}' -d 'whitelist[port]=22' "https://${{ secrets.SSH_USER }}:${{ steps.encoded.outputs.password }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=add" | jq
