name: test
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
          - name: SSH
            run: |
              ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
