name: test
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
        - name: get runner ip
          run: |
              response = $(curl https://api.ipify.org);
              echo "response=$response" >> $GITHUB_OUTPUT
