name: test

on:
  push:
    branches: [ main ]

env:
  ENDPOINT: frontend/o2switch/o2switch-ssh-whitelist/index.live.php

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Encoding Password in URI
        id: encoded_password
        run: |
          PASSWORD=$(printf %s ${{ secrets.SSH_PASSWORD }} | jq -sRr @uri )
          echo "PASSWORD=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Getting Runner IP
        id: runner_ip
        run: |
          IP=$(curl https://api.ipify.org)
          echo "IP=$IP" >> $GITHUB_OUTPUT

      - name: Getting Current Whitelist
        id: current_whitelist
        run: |
          echo "Actual whitelist : "
          
          WHITELIST=$(curl -sX GET "https://${{ secrets.SSH_USER }}:${{ steps.encoded_password.outputs.PASSWORD }}@${{ secrets.SSH_HOST }}:2083/${{ env.ENDPOINT }}?r=list")
          echo "$WHITELIST" | jq -c '.data.list[]'
          echo "WHITELIST=$WHITELIST" >> $GITHUB_OUTPUT

      - name: Adding Runner IP to Whitelist
        run: |
          IP_IS_WHITELISTED=$(echo "${{ steps.current_whitelist.outputs.WHITELIST }}" | jq '.data.list | any(.address == "${{ steps.runner_ip.outputs.IP }}")')
          
          echo "$IP_IS_WHITELISTED"
