name: test
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
        - name: get runner ip
          id: runner_ip
          run: |
              response=$(curl https://api.ipify.org)
              echo "response=$response" >> $GITHUB_OUTPUT

        - name: display runner ip
          run: echo "${{needs.id.outputs.response}}"

        - name: encode password
          id: encoded
          run:  |
              encoded=$(printf %s 'U9sV-p5XA-Bhr{' | jq -sRr @uri )
              echo "encoded=$encoded"> >> $GITHUB_OUTPUT
