name: test
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
        - name: get runner ip
          id: runner_ip
          run: |
              response=$(curl https://api.ipify.org)
              echo "response=$response" >> $GITHUB_OUTPUT

        - name: display runner ip
          run: echo "${{needs.id.outputs.response}}"

        - name: Whitelist IP on hosting & delete github old ones (o2switch)
          shell: bash
          run: |
              ENDPOINT='frontend/o2switch/o2switch-ssh-whitelist/index.live.php'
        
              echo "Get actual whitelisted IPs..."
              RESPONSE=$(curl -sX GET "https://${{ secrets.SSH_USER }}:${{ secrets.SSH_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=list")
              echo "Response: $RESPONSE"
              UNIQUE_IPS=$(echo "$RESPONSE" | jq -r '.data.list[] | .address' | sort -u)
